name: Publish a package

on:
    release:
        types: [released]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@${{github.repository_owner}}"
            - run: |
                  npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
                  npm install
              env:
                  NODE_AUTH_TOKEN: ${{github.token}}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PAT}}
